import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "2027 사업기회 준비지도 | Bizfit",
  description: "2023~2025년 기업마당 공고 33,004건의 월별 흐름과 최신 정책 변화를 살펴보는 사업기회 준비지도",
};

const years = [
  { year: 2023, total: 10214, color: "#96baf0", months: [1046,1016,1178,1018,1016,962,991,944,717,583,460,283] },
  { year: 2024, total: 9669, color: "#4e8de9", months: [968,1057,1007,906,743,818,1007,974,805,608,509,267] },
  { year: 2025, total: 13121, color: "#105ee6", months: [826,1274,1630,1710,1338,1310,1494,1124,961,557,497,400] },
];
const monthlyTotals = years[0].months.map((_, month) => years.reduce((sum, item) => sum + item.months[month], 0));
const quarters = [
  { period: "1~3월", count: 10002, share: "30.3%", title: "연초 집중 확인", insight: "3년 합산 공고가 가장 많은 분기입니다. 3월은 월별 합계 3,815건으로 최다였습니다.", action: "사업계획서와 재무·고용 증빙을 연말에 정리하고, 1월부터 주 1회 확인하세요." },
  { period: "4~6월", count: 9821, share: "29.8%", title: "상반기 후속 공고", insight: "4~6월에도 전체의 약 30%가 시작됐습니다. 2025년에는 4월이 가장 많았습니다.", action: "지역·업종 필터를 저장하고 수행기관 공고와 기업마당을 함께 확인하세요." },
  { period: "7~9월", count: 9017, share: "27.3%", title: "하반기 재점검", insight: "7월은 3년 합계 3,492건입니다. 연초에만 확인하면 놓치는 공고가 많습니다.", action: "상반기 미선정 사업의 추가모집과 추경 연계 공고를 다시 살펴보세요." },
  { period: "10~12월", count: 4164, share: "12.6%", title: "다음 해 준비", insight: "공고량은 가장 적지만 연말에 다음 사업연도 공고와 사전 안내가 나올 수 있습니다.", action: "다음 해 자금·채용·수출 계획을 확정하고 관심 사업의 공식 안내를 확인하세요." },
];
const source = "https://www.data.go.kr/data/3034791/fileData.do";
const budget = "https://www.mss.go.kr/site/smba/ex/bbs/View.do?bcIdx=1070863&cbIdx=86&parentSeq=1070863";
const supplementary = "https://www.mss.go.kr/site/smba/ex/bbs/View.do?bcIdx=1067187&cbIdx=86&parentSeq=1067187";
const modoo = "https://mss.go.kr/site/gyeongnam/ex/bbs/View.do?bcIdx=1066691&cbIdx=217";
const article = "https://v.daum.net/v/Kxxo1CnQ1h";

function SourceLink({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className="font-bold text-[#105ee6] underline decoration-[#b5cdf5] underline-offset-4 hover:decoration-[#105ee6]">{children} ↗</a>;
}
export default function PrepMap() {
  return <main className="min-h-screen bg-[#f5f8fc] text-[#09224a]">
    <header className="border-b border-[#dce6f4] bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="font-black tracking-[.16em]">BIZFIT</Link><Link href="/" className="text-sm font-bold text-[#105ee6]">맞춤 공고 찾기 →</Link></div></header>
    <section className="bg-[#071d47] text-white"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><p className="text-xs font-black tracking-[.2em] text-[#89b8ff]">2027 OPPORTUNITY PREP MAP</p><h1 className="mt-4 text-4xl font-black sm:text-5xl">2027 사업기회 준비지도</h1><p className="mt-5 max-w-3xl text-base leading-8 text-[#d0def4]">최근 완료된 3개 연도, 2023~2025년 기업마당 공고 33,004건을 신청 시작월 기준으로 분석했습니다. 실제 공고 흐름과 최신 정책 변화를 한눈에 살펴보세요.</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full border border-white/25 px-3 py-1.5">분석 기간 2023~2025년</span><span className="rounded-full border border-white/25 px-3 py-1.5">2026.09.20 확인</span><span className="rounded-full border border-white/25 px-3 py-1.5">기업마당 공개 데이터</span></div></div></section>
    <div className="mx-auto max-w-7xl space-y-12 px-5 py-11 lg:px-8">
      <section aria-label="핵심 수치" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["33,004건","3개 연도 공고 합계","2023년 10,214 · 2024년 9,669 · 2025년 13,121"],["3월","3년 합산 최다 월","3,815건 · 12월 950건"],["19일","신청기간 중앙값","유효 기간 32,942건 기준"],["27.1%","14일 이내 모집","8,913건 · 짧은 공고에 대비 필요"]].map(([number,label,detail]) => <article key={label} className="soft-card p-5 sm:p-6"><strong className="text-3xl font-black text-[#105ee6]">{number}</strong><h2 className="mt-3 font-black">{label}</h2><p className="mt-1 text-xs leading-5 text-[#64748b]">{detail}</p></article>)}</section>
      <section className="rounded-2xl border border-[#dce6f4] bg-white p-5 sm:p-8" aria-labelledby="chart-title">
        <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">THREE-YEAR MONTHLY TREND</p><h2 id="chart-title" className="mt-2 text-2xl font-black">월별 공고 흐름</h2><p className="mt-2 text-sm text-[#64748b]">같은 월의 2023·2024·2025년 공고 수를 나란히 비교했습니다.</p></div><div className="flex flex-wrap gap-3 text-xs font-bold">{years.map(item => <span key={item.year} className="flex items-center gap-1.5"><i className="h-3 w-3 rounded-sm" style={{ backgroundColor: item.color }} />{item.year}년</span>)}</div></div>
        <div className="mt-7 overflow-x-auto pb-2"><div className="min-w-[690px]"><div className="relative h-64 border-b border-[#cbd9ec] bg-[linear-gradient(to_top,#e9eff8_1px,transparent_1px)] bg-[length:100%_25%]"><div className="absolute inset-0 grid grid-cols-12 gap-2 px-1 sm:gap-3">{monthlyTotals.map((total, index) => <div key={index} className="flex h-full items-end justify-center gap-[3px]" title={`${index + 1}월 3년 합계 ${total.toLocaleString()}건`}>{years.map(item => <div key={item.year} className="w-3 rounded-t-sm transition-opacity hover:opacity-70 sm:w-4" style={{ height: `${item.months[index] / 1800 * 100}%`, backgroundColor: item.color }} title={`${item.year}년 ${index + 1}월 ${item.months[index].toLocaleString()}건`} />)}</div>)}</div></div><div className="mt-3 grid grid-cols-12 gap-2 text-center text-xs font-bold text-[#52657f] sm:gap-3">{monthlyTotals.map((_, index) => <span key={index}>{index + 1}월</span>)}</div><div className="mt-1 grid grid-cols-12 gap-2 text-center text-[10px] font-semibold tabular-nums text-[#8190a6] sm:gap-3">{monthlyTotals.map((total,index) => <span key={index}>{total.toLocaleString()}</span>)}</div></div></div>
        <p className="mt-4 text-xs text-[#718096]">아래 숫자는 각 월의 3년 합계입니다. 막대에 마우스를 올리면 연도별 공고 수를 볼 수 있습니다.</p>
        <details className="mt-5 rounded-lg bg-[#f4f7fc] p-4 text-sm"><summary className="cursor-pointer font-bold text-[#294c7c]">월별 수치표 보기</summary><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[500px] text-right text-xs"><thead><tr><th className="py-2 text-left">연도</th>{monthlyTotals.map((_,i) => <th key={i} className="px-1">{i+1}월</th>)}</tr></thead><tbody>{years.map(item => <tr key={item.year} className="border-t border-[#dce6f4]"><th className="py-2 text-left">{item.year}</th>{item.months.map((value,i) => <td key={i} className="px-1 tabular-nums">{value.toLocaleString()}</td>)}</tr>)}</tbody></table></div></details>
      </section>
      <section><p className="eyebrow">QUARTERLY ACTION MAP</p><h2 className="mt-2 text-2xl font-black">분기별로 무엇을 준비할까요?</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{quarters.map(item => <article key={item.period} className="soft-card flex flex-col p-5"><div className="flex items-start justify-between gap-2"><h3 className="text-2xl font-black">{item.period}</h3><span className="rounded-full bg-[#e9f1ff] px-2.5 py-1 text-xs font-black text-[#105ee6]">{item.share}</span></div><p className="mt-1 text-sm font-bold text-[#105ee6]">{item.title}</p><div className="mt-4 h-1.5 rounded-full bg-[#e9f1fb]"><div className="h-full rounded-full bg-[#105ee6]" style={{ width: `${Number.parseFloat(item.share) / 35 * 100}%` }} /></div><p className="mt-2 text-xs text-[#6c7d93]">3년 합계 {item.count.toLocaleString()}건</p><p className="mt-5 flex-1 text-sm leading-6">{item.insight}</p><div className="mt-5 rounded-lg bg-[#f0f5ff] p-3 text-xs leading-5"><b className="mr-2 text-[#105ee6]">준비</b>{item.action}</div></article>)}</div></section>
      <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-[#c7d9f4] bg-[#eaf3ff] p-6 sm:p-8"><p className="eyebrow">POLICY & BUDGET WATCH</p><h2 className="mt-2 text-2xl font-black">정책 변화 레이더</h2><p className="mt-2 text-sm leading-6 text-[#52657f]">과거 공고 월뿐 아니라 예산·사업명 변경도 함께 봐야 합니다.</p><div className="mt-6 space-y-3"><div className="rounded-xl bg-white p-5"><span className="rounded bg-[#e3f5ec] px-2 py-1 text-xs font-black text-[#19744c]">2026 추경 확정</span><h3 className="mt-3 font-black">중기부 1조 6,903억 원</h3><p className="mt-2 text-sm leading-6 text-[#52657f]">2026년 4월 국회에서 확정됐습니다. 수출 중소기업 4,622억, 소상공인 민생안정 4,952억, 스타트업 6,719억, 지역 제조 AI 전환 610억 원이 주요 축입니다. 하반기 공고를 살필 때 참고할 변화입니다.</p><p className="mt-3 text-xs"><SourceLink href={supplementary}>중기부 추경 발표</SourceLink></p></div><div className="rounded-xl bg-white p-5"><span className="rounded bg-[#fff0dc] px-2 py-1 text-xs font-black text-[#9b5a0a]">2027 정부 예산안 · 심의 전</span><h3 className="mt-3 font-black">중기부 18조 724억 원 편성안</h3><p className="mt-2 text-sm leading-6 text-[#52657f]">2026년 본예산보다 1조 5,491억 원 늘어난 정부안입니다. 모두의 창업 확대와 창업·기술·수출 지원 개편 방향을 확인하되, 최종 규모와 자격은 국회 심의 후 공고에서 확인해야 합니다.</p><p className="mt-3 text-xs"><SourceLink href={budget}>중기부 2027년 예산안</SourceLink></p></div></div></article>
      <aside className="rounded-2xl border border-[#dce6f4] bg-white p-6 sm:p-8"><p className="eyebrow">CHECK BEFORE APPLYING</p><h2 className="mt-2 text-2xl font-black">사업명보다 자격요건을 먼저</h2><div className="mt-5 space-y-5 text-sm leading-6"><div><b>모두의 창업과 로컬 분야</b><p className="mt-1 text-[#64748b]">2026년 모두의 창업에는 로컬 트랙이 운영됐습니다. 2027년에는 새 모집요강에서 트랙·선발 규모를 확인하세요.</p><p className="mt-1 text-xs"><SourceLink href={modoo}>공식 발표</SourceLink></p></div><div className="border-t border-[#e4ebf5] pt-5"><b>청년창업사관학교 등 개편 보도</b><p className="mt-1 text-[#64748b]">독립 사업의 전환·통합 가능성이 보도됐습니다. 보도만으로 폐지나 완전 흡수를 확정하지 않고, 최종 예산과 수행기관 공고를 확인해야 합니다.</p><p className="mt-1 text-xs"><SourceLink href={article}>관련 보도</SourceLink></p></div><div className="border-t border-[#e4ebf5] pt-5"><b>실제 신청 전 확인할 것</b><p className="mt-1 text-[#64748b]">업력·지역·업종·중복수혜 제한, 자부담, 신청 채널과 마감 시간을 원문에서 다시 확인하세요.</p></div></div></aside></section>
      <section className="rounded-2xl border border-[#dce6f4] bg-white p-6 sm:p-8"><p className="eyebrow">DATA NOTES</p><h2 className="mt-2 text-xl font-black">집계 기준과 출처</h2><div className="mt-4 grid gap-4 text-sm leading-6 text-[#5d6d83] md:grid-cols-2"><p>중소벤처기업부 ‘중소기업지원사업목록’ 공개 CSV의 2024.03.31, 2025.03.31, 2026.09.01 판본을 합쳤습니다. 신청 시작일이 2023~2025년인 항목을 선택하고 상세 URL로 중복 제거했습니다. 같은 사업의 추가모집은 별도 공고로 셉니다.</p><p>공개 파일의 판본마다 수록 범위가 달라 과거 파일을 함께 보완했습니다. 신청기간은 시작일·종료일이 유효하고 1~366일인 32,942건에서 양 끝 날짜를 포함해 계산했습니다. 공고 건수는 실제 신청자 수나 지원 예산을 뜻하지 않습니다.</p></div><p className="mt-4 text-xs"><SourceLink href={source}>공공데이터포털 원자료 · 중소벤처기업부, 공공누리 제1유형</SourceLink></p></section>
    </div><footer className="mt-10 border-t border-[#dce6f4] bg-white px-5 py-7 text-center text-xs text-[#718096]">© 2026 Bizfit. All rights reserved.</footer>
  </main>;
}
