import Link from "next/link";

const monthly = [727, 1283, 1583, 1684, 1355, 1345, 1574, 1140, 984, 586, 514, 385];
const seasons = [
  { period: "1~3월", title: "대형 정부사업 첫 공고", all: 27, first: 59, fields: ["정책자금·융자 1.4배", "소상공인 1.1배", "수출 1.1배"], detail: "초기·창업도약패키지, 기술혁신개발 R&D, 수출바우처 등은 전년도 공고와 2027년 제도 변경을 함께 확인하세요.", prep: "전년 10~12월에 사업계획서·증빙 초안을 준비하세요." },
  { period: "4~6월", title: "공고량 최다 · 지역사업", all: 33, first: 30, fields: ["창업·사업화 1.1배", "교육·컨설팅 1.1배", "AI·디지털 1.1배"], detail: "지자체 공고 비중 68%. 시·군 단위 판로·마케팅·디지털 전환 사업이 많았습니다.", prep: "내 지역·업종 공고를 주 단위로 확인하세요." },
  { period: "7~9월", title: "추가모집 시즌", all: 28, first: 7, fields: ["시설·장비 1.2배", "정책자금·융자 1.1배"], detail: "공고의 45%가 추가·재공고·차수 공고였습니다. 7월은 연중 두 번째 봉우리입니다.", prep: "상반기에 놓친 사업의 추가모집을 확인하세요." },
  { period: "10~12월", title: "차년도 선공고", all: 11, first: 4, fields: ["시설·장비 1.2배", "AI·디지털 1.2배"], detail: "공고량은 적지만 정책자금 등 차년도 사업이 12월 말부터 열릴 수 있습니다.", prep: "차년도 사업계획과 자금 계획을 확정하세요." },
];
const repeat = [
  ["중소기업 정책자금 융자", "2024.12.26", "2025.12.23", "2026년 12월 말경"],
  ["소상공인 정책자금", "2024.12.26", "2025.12.30", "2026년 12월 말경"],
  ["수출바우처", "2025.01.07", "2025.12.17", "12~1월경"],
  ["초기창업패키지", "2025.02.24", "2026.01.06", "1~2월경"],
  ["창업도약패키지", "2025.02.20", "2026.01.06", "1~2월경"],
  ["중소기업기술혁신개발사업", "2025.01.17", "2026.01.26", "1월경"],
  ["희망리턴패키지 재기사업화", "2025.01.20", "2026.01.30", "1월경"],
  ["온라인 브랜드 소상공인 육성(TOPS)", "2025.01.31", "2026.01.21", "1월경"],
  ["재도전성공패키지", "2025.02.12", "2026.02.11", "2월경"],
  ["데이터바우처", "2025.02.12", "2026.02.27", "2월경"],
  ["예비창업패키지", "2025.02.24", "2026.03.06", "2027년 별도 공고 불확실"],
];
const officialBudget = "https://www.mss.go.kr/site/smba/ex/bbs/View.do?bcIdx=1070863&cbIdx=86";
const officialModoo = "https://mss.go.kr/site/gyeongnam/ex/bbs/View.do?bcIdx=1066691&cbIdx=217";
const report = "https://v.daum.net/v/Kxxo1CnQ1h";

export default function PrepMap() {
  return <main className="min-h-screen bg-[var(--mist)] text-[var(--navy)]">
    <header className="border-b border-[#dfe8f5] bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="font-black tracking-[.16em]">BIZFIT</Link><Link href="/" className="text-sm font-bold text-[var(--blue)]">맞춤 공고 찾기 →</Link></div></header>
    <section className="bg-[var(--navy)] text-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-black tracking-[.2em] text-[#82b4ff]">2027 OPPORTUNITY PREP MAP</p><h1 className="mt-4 text-4xl font-black sm:text-5xl">2027 사업기회 준비지도</h1><p className="mt-5 max-w-3xl text-base leading-8 text-[#cbd9ef]">기업마당의 2025년 1월~2026년 9월 마감 공고 20,820건을 신청 시작월 기준으로 분석한 자료를 시각화했습니다. 날짜를 예측하지 않고, 언제 무엇을 준비할지 보여드립니다.</p><p className="mt-4 text-xs leading-6 text-[#95a9c9]">통계: 사용자 제공 분석 · 원자료/집계 코드는 아직 검증되지 않았습니다. 2027년 정책·예산·모집 일정은 국회 심의와 기관 공고에 따라 달라질 수 있습니다.</p></div></section>
    <div className="mx-auto max-w-7xl space-y-12 px-5 py-12 lg:px-8">
      <section className="grid gap-3 sm:grid-cols-3">{[["4월", "2025년 공고 최다", "1,684건 · 12월 385건"], ["59%", "반복 중앙부처 사업 첫 공고", "457개 중 1~3월 비율"], ["17일", "신청기간 중앙값", "39%는 14일 이내 마감"]].map(([value, label, detail]) => <article key={value} className="soft-card p-6"><strong className="text-4xl text-[var(--blue)]">{value}</strong><h2 className="mt-3 font-black">{label}</h2><p className="mt-1 text-sm text-[#66738a]">{detail}</p></article>)}</section>
      <section className="rounded-2xl border border-[#dfe8f5] bg-white p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">2025 MONTHLY VOLUME</p><h2 className="mt-2 text-2xl font-black">월별 공고 수</h2></div><span className="text-xs text-[#66738a]">2025년 · 신청 시작월 기준 · 사용자 제공 집계</span></div><div className="mt-7 grid grid-cols-6 gap-2 sm:grid-cols-12">{monthly.map((count, index) => <div key={index} className="flex flex-col items-center justify-end gap-2"><span className="text-[10px] font-bold tabular-nums text-[#53627c] sm:text-xs">{count.toLocaleString()}</span><div className="flex h-36 w-full items-end rounded-md bg-[#f0f5fd]"><div className={`w-full rounded-md ${index === 3 ? "bg-[var(--blue)]" : "bg-[#96b9f2]"}`} style={{ height: `${Math.max(8, count / 1684 * 100)}%` }} /></div><span className="text-xs font-bold">{index + 1}월</span></div>)}</div><p className="mt-5 text-xs leading-5 text-[#718096]">추가·재공고·차수 구분과 2026년 월별 비교는 검증된 원자료가 연결되면 별도 계열로 표시합니다.</p></section>
      <section><p className="eyebrow">PREPARATION BY SEASON</p><h2 className="mt-2 text-2xl font-black">분기별 준비 포인트</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{seasons.map((season) => <article key={season.period} className="soft-card flex flex-col p-5"><h3 className="text-2xl font-black">{season.period}</h3><p className="mt-1 border-b border-[#dce7fa] pb-3 text-sm font-black text-[var(--blue)]">{season.title}</p><div className="mt-4 space-y-2 text-sm">{[["전체 공고", season.all], ["반복사업 첫 공고", season.first]].map(([label, value]) => <div key={String(label)} className="flex items-center gap-2"><span className="min-w-[96px] text-xs text-[#60708a]">{label}</span><div className="h-2 flex-1 rounded-full bg-[#edf3fd]"><div className="h-full rounded-full bg-[var(--blue)]" style={{ width: `${value}%` }} /></div><b className="w-8 text-right text-xs">{value}%</b></div>)}</div><p className="mt-5 text-xs font-black text-[#60708a]">평소보다 많이 나오는 분야</p><div className="mt-2 flex flex-wrap gap-1">{season.fields.map((field) => <span key={field} className="rounded bg-[#edf4ff] px-2 py-1 text-xs font-bold text-[#1855ba]">{field}</span>)}</div><p className="mt-4 flex-1 text-sm leading-6">{season.detail}</p><div className="mt-5 rounded-lg bg-[#f3f7ff] p-3 text-xs leading-5"><strong className="mr-2 text-[var(--blue)]">준비</strong>{season.prep}</div></article>)}</div></section>
      <section className="rounded-2xl border border-[#dfe8f5] bg-white"><div className="border-b border-[#dfe8f5] p-5 sm:p-7"><p className="eyebrow">REPEAT PROGRAMS</p><h2 className="mt-2 text-2xl font-black">주요 반복 사업의 첫 공고 시점</h2><p className="mt-2 text-sm text-[#66738a]">사업연도별 첫 공고의 신청 시작일. 오른쪽은 신청일 예측이 아니라 확인 권장 시기입니다.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#f7faff] text-xs text-[#61718a]"><tr><th className="px-5 py-3">사업</th><th className="px-5 py-3">2025년 사업</th><th className="px-5 py-3">2026년 사업</th><th className="px-5 py-3">2027년 확인 시기</th></tr></thead><tbody>{repeat.map(([name, y25, y26, timing]) => <tr key={name} className="border-t border-[#e6edf8]"><th className="px-5 py-3 font-black">{name}</th><td className="px-5 py-3">{y25}</td><td className="px-5 py-3">{y26}</td><td className="px-5 py-3"><span className="rounded bg-[#fff1e2] px-2 py-1 font-bold text-[#a65b14]">{timing}</span></td></tr>)}</tbody></table></div><p className="p-5 text-xs leading-5 text-[#718096]">주의: 예비창업패키지 등 개편 가능성이 있는 사업은 과거 시점이 2027년 독립 공고를 보장하지 않습니다.</p></section>
      <section className="rounded-2xl border border-[#bad1f9] bg-[#eaf3ff] p-6 sm:p-8"><p className="eyebrow">POLICY CHANGE WATCH · 2026.09.19 확인</p><h2 className="mt-2 text-2xl font-black">2027년 정책 변경을 함께 보세요</h2><div className="mt-5 grid gap-3 lg:grid-cols-3"><article className="rounded-xl bg-white p-5"><span className="text-xs font-black text-[#a65b14]">정부 예산안 · 확정 전</span><h3 className="mt-2 font-black">모두의 창업 확대</h3><p className="mt-2 text-sm leading-6 text-[#586981]">중기부 2027년 예산안에 4,411억 원, 지원 규모 2만 명이 제시됐습니다. 확정 예산과 모집요강은 별도로 확인해야 합니다.</p><a className="mt-3 inline-block text-xs font-bold text-[var(--blue)]" href={officialBudget} target="_blank" rel="noopener noreferrer">중기부 예산안 ↗</a></article><article className="rounded-xl bg-white p-5"><span className="text-xs font-black text-[#a65b14]">보도된 개편 · 확정 공고 전</span><h3 className="mt-2 font-black">청년창업사관학교 전환 보도</h3><p className="mt-2 text-sm leading-6 text-[#586981]">2027년 독립 예산이 편성되지 않고 기존 거점을 재도전성공학교에 활용한다는 보도가 있습니다. 국회 심의·후속 공고 전에는 폐지 확정으로 단정하지 않습니다.</p><a className="mt-3 inline-block text-xs font-bold text-[var(--blue)]" href={report} target="_blank" rel="noopener noreferrer">관련 보도 ↗</a></article><article className="rounded-xl bg-white p-5"><span className="text-xs font-black text-[#24735d]">2026년 공식 운영 확인</span><h3 className="mt-2 font-black">로컬 분야는 모두의 창업 트랙</h3><p className="mt-2 text-sm leading-6 text-[#586981]">2026년 모두의 창업에는 일반·기술과 로컬 트랙이 운영됐습니다. 이것만으로 신사업창업사관학교·로컬크리에이터의 2027년 완전 흡수까지 확정할 수는 없습니다.</p><a className="mt-3 inline-block text-xs font-bold text-[var(--blue)]" href={officialModoo} target="_blank" rel="noopener noreferrer">중기부 모집 발표 ↗</a></article></div><p className="mt-5 text-xs leading-6 text-[#586981]">공고명·예산·지원대상·접수기간은 변경될 수 있습니다. 이 지도는 준비용이며 신청 가능 여부는 해당 기관의 최신 공고문이 기준입니다.</p></section>
      <section className="grid gap-3 md:grid-cols-3">{[["A · 확정 공고", "실제로 공고된 사업", "모집 기간과 D-day는 기업마당·K-Startup 원문을 기준으로 표시합니다."], ["B · 마감 예정", "저장한 공고의 마감", "신청기간이 짧으므로 원하면 D-7·D-3에 다시 알려드립니다."], ["C · 예상 공고", "준비 기간만 안내", "과거 첫 공고 시점을 근거로 월 범위만 제시합니다. 확정 날짜로 표시하지 않습니다."]].map(([code, title, detail]) => <article key={code} className="soft-card p-6"><span className="text-sm font-black text-[var(--blue)]">{code}</span><h3 className="mt-3 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[#66738a]">{detail}</p></article>)}</section>
    </div><footer className="mt-10 border-t border-[#dfe8f5] bg-white px-5 py-7 text-center text-xs text-[#718096]">Bizfit · 통계 출처와 2027년 개편안의 확정 상태를 구분해 확인하세요.</footer>
  </main>;
}
